# -*- mode: ruby -*-
# vi: set ft=ruby :

  # First I will configure my Master server
  Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "192.168.56.2"
      master.vm.network "forwarded_port", guest: 80, host: 8088
    end
  config.vm.define "slave" do |slave|
      slave.vm.box = "ubuntu/focal64"
      slave.vm.hostname = "slave"
      slave.vm.network "private_network", ip: "192.168.56.3"
      slave.vm.network "forwarded_port", guest: 80, host: 8089
    end
  end